### ISSUE TITLE
Enhancement proposal: Comprehensive 'Getting Started Guide' and documentation for game objectives and mechanics

### ISSUE THREAD

**Issue by kilianar** [Ankylotech/SnakePVP#3]
I believe it would be helpful to provide a comprehensive documentation or a "getting started guide." This guide should delve into the game's objectives in more detail than the existing README. It should outline how many points are awarded by eating the various types of fruits and the effect each fruit triggers. Additionally, it would be beneficial to include an explanation of the structure of the arguments passed to the agent. It might be wise to include a well-commented example featuring a simple AI agent to demonstrate the practical
usage.

**Comment by Ankylotech** [comment]
Opened branch with initial implementations, open for feedback
